In [3]:
import seaborn as sns
import pandas as pd


# Q1

Explain the difference between SimpleImputer and KNNImputer, and use them on this data.

data = {'Age': [25, 30, None, 45, 40], 'Fare': [100, None, 80, 75, 60]}



---



In [4]:
import pandas as pd

In [5]:
data = {'Age': [25, 30, None, 45, 40], 'Fare': [100, None, 80, 75, 60]}

In [6]:
data=pd.DataFrame(data)

In [7]:
data.head()

Age   Fare
0  25.0  100.0
1  30.0    NaN
2   NaN   80.0
3  45.0   75.0
4  40.0   60.0

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Age     4 non-null      float64
 1   Fare    4 non-null      float64
dtypes: float64(2)
memory usage: 212.0 bytes


In [9]:
from sklearn.impute import SimpleImputer, KNNImputer

In [10]:
imputer=SimpleImputer(strategy='mean')

In [11]:
trdata = imputer.fit_transform(data)

In [12]:
pd.DataFrame(trdata, columns= data.columns).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Age     5 non-null      float64
 1   Fare    5 non-null      float64
dtypes: float64(2)
memory usage: 212.0 bytes


In [98]:
trdata

array([[ 25., 100.],
       [ 30.,  80.],
       [ 35.,  80.],
       [ 45.,  75.],
       [ 40.,  60.]])

In [13]:
imputer = KNNImputer(n_neighbors=2)

In [14]:
trdata = imputer.fit_transform(data)

In [15]:
pd.DataFrame(trdata, columns= data.columns)

Age   Fare
0  25.0  100.0
1  30.0   80.0
2  35.0   80.0
3  45.0   75.0
4  40.0   60.0

# Q2

Use DictVectorizer to transform a list of dictionaries into a feature matrix. Also use FeatureHasher.

data = [{'city': 'New York', 'temperature': 21},
        {'city': 'San Francisco', 'temperature': 18},
        {'city': 'Chicago', 'temperature': 15}]

In [16]:
data = [{'city': 'New York', 'temperature': 21}, {'city': 'San Francisco', 'temperature': 18}, {'city': 'Chicago', 'temperature': 15}]

In [17]:
from sklearn.feature_extraction import DictVectorizer

In [18]:
dv= DictVectorizer()

In [19]:
dv.fit_transform(data).toarray()

array([[ 0.,  1.,  0., 21.],
       [ 0.,  0.,  1., 18.],
       [ 1.,  0.,  0., 15.]])

In [20]:
from sklearn.feature_extraction import FeatureHasher

In [21]:
? FeatureHasher

Init signature:
 FeatureHasher(
    n_features=1048576,
    *,
    input_type='dict',
    dtype=<class 'numpy.float64'>,
    alternate_sign=True,
)
Docstring:     
Implements feature hashing, aka the hashing trick.

This class turns sequences of symbolic feature names (strings) into
scipy.sparse matrices, using a hash function to compute the matrix column
corresponding to a name. The hash function employed is the signed 32-bit
version of Murmurhash3.

Feature names of type byte string are used as-is. Unicode strings are
converted to UTF-8 first, but no Unicode normalization is done.
Feature values must be (finite) numbers.

This class is a low-memory alternative to DictVectorizer and
CountVectorizer, intended for large-scale (online) learning and situations
where memory is tight, e.g. when running prediction code on embedded
devices.

For an efficiency comparison of the different feature extractors, see
:ref:`sphx_glr_auto_examples_text_plot_hashing_vs_dict_vectorizer.py`.

Read more i

In [22]:
fh=FeatureHasher(n_features=4)

In [23]:
fh.fit_transform(data).toarray()

array([[  0., -21.,   0.,  -1.],
       [ -1., -18.,   0.,   0.],
       [  0., -15.,   0.,   1.]])

# Q3

df = sns.load_dataset('titanic')

df.head()

Use SimpleImputer to fill missing values in the Age column with the mean.

In [24]:
df = sns.load_dataset('titanic')

df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [25]:
type(df['age'])

pandas.core.series.Series

In [26]:
age= df[['age']]

In [27]:
type(age)

pandas.core.frame.DataFrame

In [28]:
imputer=SimpleImputer(strategy ='mean')

In [29]:
transformed_age=imputer.fit_transform(df[['age']])

In [30]:
df['age']=transformed_age

In [31]:
df['age'].isna().sum()

0

# Q4

Use KNNImputer to fill missing values in both Age and Fare columns based on their nearest neighbors.

In [32]:
data=df[['age', 'fare']]

In [33]:
data.head()

age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [34]:
knn_imputer=KNNImputer(n_neighbors=5)

In [35]:
imputed_data=knn_imputer.fit_transform(data)

In [36]:
imputed_data

array([[22.        ,  7.25      ],
       [38.        , 71.2833    ],
       [26.        ,  7.925     ],
       ...,
       [29.69911765, 23.45      ],
       [26.        , 30.        ],
       [32.        ,  7.75      ]])

In [37]:
imputed_datadf = pd.DataFrame(imputed_data, columns= ['age', 'fare'])

In [38]:
df[['age', 'fare']] = imputed_datadf

In [39]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [40]:
df.isna().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

# Q5

Use OneHotEncoder to encode the categorical Sex and Embarked columns.

In [41]:
from sklearn.preprocessing import OneHotEncoder
onehot=OneHotEncoder(sparse_output=False)

In [42]:
?OneHotEncoder

Init signature:
OneHotEncoder(
    *,
    categories='auto',
    drop=None,
    sparse_output=True,
    dtype=<class 'numpy.float64'>,
    handle_unknown='error',
    min_frequency=None,
    max_categories=None,
    feature_name_combiner='concat',
)
Docstring:     
Encode categorical features as a one-hot numeric array.

The input to this transformer should be an array-like of integers or
strings, denoting the values taken on by categorical (discrete) features.
The features are encoded using a one-hot (aka 'one-of-K' or 'dummy')
encoding scheme. This creates a binary column for each category and
returns a sparse matrix or dense array (depending on the ``sparse_output``
parameter).

By default, the encoder derives the categories based on the unique values
in each feature. Alternatively, you can also specify the `categories`
manually.

This encoding is needed for feeding categorical data to many scikit-learn
estimators, notably linear models and SVMs with the standard kernels.

Note: a o

In [43]:
data = df[['sex', 'embarked']]

In [44]:
data.head()

sex embarked
0    male        S
1  female        C
2  female        S
3  female        S
4    male        S

In [45]:
data['embarked'].value_counts()

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [46]:
imp=SimpleImputer(strategy='most_frequent')

In [47]:
imputed_embarked =imp.fit_transform(data[['embarked']])

In [48]:
imputed_embarked.shape

(891, 1)

In [49]:
imputed_embarked = imputed_embarked.flatten()

In [50]:
data['embarked'] = imputed_embarked

C:\Users\pallavi\AppData\Local\Temp\ipykernel_5956\3362323026.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['embarked'] = imputed_embarked


In [51]:
data.isna().sum()

sex         0
embarked    0
dtype: int64

In [52]:
data['sex'].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [53]:
encoded_data=onehot.fit_transform(data)

In [54]:
encoded_data

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [55]:
onehot.get_feature_names_out()

array(['sex_female', 'sex_male', 'embarked_C', 'embarked_Q', 'embarked_S'],
      dtype=object)

In [56]:
encoded_df = pd.DataFrame(encoded_data, columns=onehot.get_feature_names_out())

In [57]:
encoded_df.head()

sex_female  sex_male  embarked_C  embarked_Q  embarked_S
0         0.0       1.0         0.0         0.0         1.0
1         1.0       0.0         1.0         0.0         0.0
2         1.0       0.0         0.0         0.0         1.0
3         1.0       0.0         0.0         0.0         1.0
4         0.0       1.0         0.0         0.0         1.0

# Q6
Use LabelEncoder to encode the Sex column.


In [58]:
from sklearn.preprocessing import LabelEncoder
enc= LabelEncoder()
encoded_sex= enc.fit_transform(df['sex'])

In [59]:
df['sex'] = encoded_sex

# Q7
 Use OrdinalEncoder to encode the Embarked column, assuming some ordinal ranking of the ports.

# Q8
Create a pipeline that imputes missing values for the Age column and encodes the Sex and Embarked columns using OneHotEncoder.

In [60]:
df = sns.load_dataset('titanic')

df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [61]:
df['deck'].value_counts()

deck
C    59
B    47
D    33
E    32
A    15
F    13
G     4
Name: count, dtype: int64

In [62]:
df['class'].value_counts()

class
Third     491
First     216
Second    184
Name: count, dtype: int64

In [63]:
from sklearn.pipeline import Pipeline

In [64]:
from sklearn.compose import ColumnTransformer

In [65]:
pipe = Pipeline([('preprocessor' ,ColumnTransformer([('imputer' ,  SimpleImputer(strategy = 'mean'), ['age']), ('encoder', OneHotEncoder(sparse_output=False), ['sex', 'embarked'])], remainder = 'passthrough') )])

In [66]:
dftransformed = pipe.fit_transform(df)

In [67]:
dftransformed

array([[22.0, 0.0, 1.0, ..., 'Southampton', 'no', False],
       [38.0, 1.0, 0.0, ..., 'Cherbourg', 'yes', False],
       [26.0, 1.0, 0.0, ..., 'Southampton', 'yes', True],
       ...,
       [29.69911764705882, 1.0, 0.0, ..., 'Southampton', 'no', False],
       [26.0, 0.0, 1.0, ..., 'Cherbourg', 'yes', True],
       [32.0, 0.0, 1.0, ..., 'Queenstown', 'no', True]], dtype=object)

In [68]:
?Pipeline

Init signature: Pipeline(steps, *, transform_input=None, memory=None, verbose=False)
Docstring:     
A sequence of data transformers with an optional final predictor.

`Pipeline` allows you to sequentially apply a list of transformers to
preprocess the data and, if desired, conclude the sequence with a final
:term:`predictor` for predictive modeling.

Intermediate steps of the pipeline must be transformers, that is, they
must implement `fit` and `transform` methods.
The final :term:`estimator` only needs to implement `fit`.
The transformers in the pipeline can be cached using ``memory`` argument.

The purpose of the pipeline is to assemble several steps that can be
cross-validated together while setting different parameters. For this, it
enables setting parameters of the various steps using their names and the
parameter name separated by a `'__'`, as in the example below. A step's
estimator may be replaced entirely by setting the parameter with its name
to another estimator, or a trans

In [69]:
pipe

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('imputer', SimpleImputer(),
                                                  ['age']),
                                                 ('encoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['sex', 'embarked'])]))])

In [70]:
pipe.named_steps['preprocessor']

ColumnTransformer(remainder='passthrough',
                  transformers=[('imputer', SimpleImputer(), ['age']),
                                ('encoder', OneHotEncoder(sparse_output=False),
                                 ['sex', 'embarked'])])

In [71]:
coltrans = ColumnTransformer([('imputer' ,  SimpleImputer(strategy = 'mean'), ['age']), ('encoder', OneHotEncoder(sparse_output=False), ['sex', 'embarked'])], remainder = 'passthrough')

In [72]:
transformed_data =coltrans.fit_transform(df)

In [73]:
ohe=list(coltrans['encoder'].get_feature_names_out())

In [74]:
rem= df.columns.difference(['age', 'sex' ,  'embarked']).tolist()

In [75]:
df.columns.difference(['age', 'sex' ,  'embarked']).tolist()

['adult_male',
 'alive',
 'alone',
 'class',
 'deck',
 'embark_town',
 'fare',
 'parch',
 'pclass',
 'sibsp',
 'survived',
 'who']

In [76]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [77]:
coltrans.get_feature_names_out()

array(['imputer__age', 'encoder__sex_female', 'encoder__sex_male',
       'encoder__embarked_C', 'encoder__embarked_Q',
       'encoder__embarked_S', 'encoder__embarked_nan',
       'remainder__survived', 'remainder__pclass', 'remainder__sibsp',
       'remainder__parch', 'remainder__fare', 'remainder__class',
       'remainder__who', 'remainder__adult_male', 'remainder__deck',
       'remainder__embark_town', 'remainder__alive', 'remainder__alone'],
      dtype=object)

In [78]:
# rem=['survived', 'pclass', 'sex', 'sibsp', 'parch', 'fare',
#        'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
#        'alive', 'alone']

In [79]:
cols=['age'] + ohe + rem

In [80]:
trdf = pd.DataFrame(transformed_data, columns =coltrans.get_feature_names_out())

In [81]:
trdf.head()

imputer__age encoder__sex_female encoder__sex_male encoder__embarked_C  \
0         22.0                 0.0               1.0                 0.0   
1         38.0                 1.0               0.0                 1.0   
2         26.0                 1.0               0.0                 0.0   
3         35.0                 1.0               0.0                 0.0   
4         35.0                 0.0               1.0                 0.0   

  encoder__embarked_Q encoder__embarked_S encoder__embarked_nan  \
0                 0.0                 1.0                   0.0   
1                 0.0                 0.0                   0.0   
2                 0.0                 1.0                   0.0   
3                 0.0                 1.0                   0.0   
4                 0.0                 1.0                   0.0   

  remainder__survived remainder__pclass remainder__sibsp remainder__parch  \
0                   0                 3                1                0   
1                   1                 1                1                0   
2                   1                 3                0                0   
3                   1                 1                1                0   
4                   0                 3                0                0   

  remainder__fare remainder__class remainder__who remainder__adult_male  \
0            7.25            Third            man                  True   
1         71.2833            First          woman                 False   
2           7.925            Third          woman                 False   
3            53.1            First          woman                 False   
4            8.05            Third            man                  True   

  remainder__deck remainder__embark_town remainder__alive remainder__alone  
0             NaN            Southampton               no            False  
1               C              Cherbourg              yes            False  
2             NaN            Southampton              yes             True  
3               C            Southampton              yes            False  
4             NaN            Southampton               no             True

# Q9
Use ColumnTransformer to apply OneHotEncoder to Sex and Embarked, and scale numerical columns like Age and Fare.

# Q10
Use SelectKBest to select the top 2 features that are most correlated with survival (Survived).

In [82]:
from sklearn.feature_selection import SelectKBest

In [83]:
trdf.isna().sum()

imputer__age                0
encoder__sex_female         0
encoder__sex_male           0
encoder__embarked_C         0
encoder__embarked_Q         0
encoder__embarked_S         0
encoder__embarked_nan       0
remainder__survived         0
remainder__pclass           0
remainder__sibsp            0
remainder__parch            0
remainder__fare             0
remainder__class            0
remainder__who              0
remainder__adult_male       0
remainder__deck           688
remainder__embark_town      2
remainder__alive            0
remainder__alone            0
dtype: int64

In [84]:
trdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   imputer__age            891 non-null    object
 1   encoder__sex_female     891 non-null    object
 2   encoder__sex_male       891 non-null    object
 3   encoder__embarked_C     891 non-null    object
 4   encoder__embarked_Q     891 non-null    object
 5   encoder__embarked_S     891 non-null    object
 6   encoder__embarked_nan   891 non-null    object
 7   remainder__survived     891 non-null    object
 8   remainder__pclass       891 non-null    object
 9   remainder__sibsp        891 non-null    object
 10  remainder__parch        891 non-null    object
 11  remainder__fare         891 non-null    object
 12  remainder__class        891 non-null    object
 13  remainder__who          891 non-null    object
 14  remainder__adult_male   891 non-null    object
 15  remain

In [85]:
X = trdf[['imputer__age', 'remainder__fare']]

In [86]:
y=trdf['remainder__survived']

In [87]:
?SelectKBest

Init signature: SelectKBest(score_func=<function f_classif at 0x000002B27A357920>, *, k=10)
Docstring:     
Select features according to the k highest scores.

Read more in the :ref:`User Guide <univariate_feature_selection>`.

Parameters
----------
score_func : callable, default=f_classif
    Function taking two arrays X and y, and returning a pair of arrays
    (scores, pvalues) or a single array with scores.
    Default is f_classif (see below "See Also"). The default function only
    works with classification tasks.

    .. versionadded:: 0.18

k : int or "all", default=10
    Number of top features to select.
    The "all" option bypasses selection, for use in a parameter search.

Attributes
----------
scores_ : array-like of shape (n_features,)
    Scores of features.

pvalues_ : array-like of shape (n_features,)
    p-values of feature scores, None if `score_func` returned only scores.

n_features_in_ : int
    Number of features seen during :term:`fit`.

    .. versionadded:: 

In [88]:
selector= SelectKBest(k=1)

In [89]:
Xnew = selector.fit_transform(X, y)

In [90]:
Xnew.shape

(891, 1)

# Q11
Use RFE (Recursive Feature Elimination) with a logistic regression model to select the top 3 features for predicting survival.

In [91]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

In [92]:
?RFE

Init signature:
RFE(
    estimator,
    *,
    n_features_to_select=None,
    step=1,
    verbose=0,
    importance_getter='auto',
)
Docstring:     
Feature ranking with recursive feature elimination.

Given an external estimator that assigns weights to features (e.g., the
coefficients of a linear model), the goal of recursive feature elimination
(RFE) is to select features by recursively considering smaller and smaller
sets of features. First, the estimator is trained on the initial set of
features and the importance of each feature is obtained either through
any specific attribute or callable.
Then, the least important features are pruned from current set of features.
That procedure is recursively repeated on the pruned set until the desired
number of features to select is eventually reached.

Read more in the :ref:`User Guide <rfe>`.

Parameters
----------
estimator : ``Estimator`` instance
    A supervised learning estimator with a ``fit`` method that provides
    information about

In [93]:
rfe= RFE(LinearRegression(), n_features_to_select=1)


In [94]:
XNEW=rfe.fit_transform(X, y)

In [95]:
XNEW.shape

(891, 1)

# Q12

Use FunctionTransformer to apply a log transformation to the Fare column.

In [96]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np
fn=FunctionTransformer(np.log1p)

In [97]:
xnew = fn.fit_transform(df['fare'])

# Q13
Create a pipeline that:  

Imputes missing values in the 'age' column using the mean.  

Imputes missing values in the 'embarked' column using the most frequent strategy.  

Scales the 'fare' and 'age' columns using StandardScaler.  

One-hot encodes the 'sex' and 'embarked' columns.


# Q14
Create a pipeline that:

Imputes missing values in the 'age' column using the mean.

Scales the 'fare' column using StandardScaler.

One-hot encodes the 'sex' column.
Passes through the 'pclass' column without any transformation.

Retains the original 'survived' column without any transformation.